"""Core contracts. Dependency-free by policy.

Nothing in ``indexer.core`` imports a third-party package, and nothing in it
names a concrete implementation. A project that adopts the frame inherits these
types and no choices.
"""

from indexer.core.accounting import (
    Accountant,
    CacheOutcome,
    InMemoryAccountant,
    StageFingerprint,
    StageRun,
)
from indexer.core.cache import ArtifactStore, CacheKey, CacheStore, NullCache, cache_key
from indexer.core.document import (
    Block,
    BlockKind,
    MediaRef,
    ParsedDocument,
    SourceDocument,
    Table,
    TableCell,
)
from indexer.core.errors import (
    ConfigError,
    ContractViolation,
    DocumentError,
    IndexerError,
    StageError,
)
from indexer.core.ids import (
    BuildId,
    ContentHash,
    DocumentId,
    UnitId,
    hash_bytes,
    hash_obj,
    hash_text,
    make_document_id,
    make_unit_id,
)
from indexer.core.ledger import ChangeKind, DocumentRecord, Ledger, PlannedChange, diff_units
from indexer.core.manifest import BuildManifest, CorpusStats, IndexStats
from indexer.core.predicate import (
    Aggregation,
    And,
    Compare,
    Exists,
    In,
    Not,
    Op,
    Or,
    Predicate,
    StructuredQuery,
    TextMatch,
    evaluate,
)
from indexer.core.provenance import BBox, PageRef, Provenance, Span
from indexer.core.query import Query, QueryType, RouteDecision, RoutePath, RouteTarget
from indexer.core.registry import REGISTRY, Registration, Registry, register, resolve
from indexer.core.results import Hit, RankedList, RecordSet, RetrievalResponse, RetrievalStep
from indexer.core.stages import (
    KIND_DENSE,
    KIND_LEXICAL,
    KIND_STRUCTURED,
    KIND_VISUAL,
    CorpusScanner,
    EnrichContext,
    Enricher,
    Fuser,
    Index,
    IndexKind,
    IndexQuery,
    IndexStatsView,
    IndexWriteReceipt,
    Parser,
    RelatedDocument,
    Reranker,
    Retriever,
    Router,
    Segmenter,
    StageContext,
    StructuredCapable,
)
from indexer.core.unit import (
    ContextScope,
    EnrichedUnit,
    Enrichment,
    FieldValue,
    Unit,
    UnitKind,
)

__all__ = [
    "KIND_DENSE",
    "KIND_LEXICAL",
    "KIND_STRUCTURED",
    "KIND_VISUAL",
    "REGISTRY",
    "Accountant",
    "Aggregation",
    "And",
    "ArtifactStore",
    "BBox",
    "Block",
    "BlockKind",
    "BuildId",
    "BuildManifest",
    "CacheKey",
    "CacheOutcome",
    "CacheStore",
    "ChangeKind",
    "Compare",
    "ConfigError",
    "ContentHash",
    "ContextScope",
    "ContractViolation",
    "CorpusScanner",
    "CorpusStats",
    "DocumentError",
    "DocumentId",
    "DocumentRecord",
    "EnrichContext",
    "EnrichedUnit",
    "Enricher",
    "Enrichment",
    "Exists",
    "FieldValue",
    "Fuser",
    "Hit",
    "In",
    "InMemoryAccountant",
    "Index",
    "IndexKind",
    "IndexQuery",
    "IndexStats",
    "IndexStatsView",
    "IndexWriteReceipt",
    "IndexerError",
    "Ledger",
    "MediaRef",
    "Not",
    "NullCache",
    "Op",
    "Or",
    "PageRef",
    "ParsedDocument",
    "Parser",
    "PlannedChange",
    "Predicate",
    "Provenance",
    "Query",
    "QueryType",
    "RankedList",
    "RecordSet",
    "Registration",
    "Registry",
    "RelatedDocument",
    "Reranker",
    "RetrievalResponse",
    "RetrievalStep",
    "Retriever",
    "RouteDecision",
    "RoutePath",
    "RouteTarget",
    "Router",
    "Segmenter",
    "SourceDocument",
    "Span",
    "StageContext",
    "StageError",
    "StageFingerprint",
    "StageRun",
    "StructuredCapable",
    "StructuredQuery",
    "Table",
    "TableCell",
    "TextMatch",
    "Unit",
    "UnitId",
    "UnitKind",
    "cache_key",
    "diff_units",
    "evaluate",
    "hash_bytes",
    "hash_obj",
    "hash_text",
    "make_document_id",
    "make_unit_id",
    "register",
    "resolve",
]
